const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const ROOT=path.resolve(__dirname,'..');
const OUTPUT=path.join(ROOT,'dist');

// A deliberately bounded CommonJS bundle: only these shared modules and the
// two browser-safe libraries can be included. AI, keys and server code cannot.
function bundle(){
  const modules=[],ids=new Map();
  const allowed=new Set(['assets/static-demo-entry.cjs','server/document.cjs','server/demo.cjs','server/errors.cjs','server/parties.cjs']);
  function add(filename){
    if(ids.has(filename))return ids.get(filename);
    const relative=path.relative(ROOT,filename).replace(/\\/g,'/');
    if(!allowed.has(relative)&&!relative.startsWith('node_modules/diff/libcjs/')&&relative!=='node_modules/fflate/lib/browser.cjs')throw new Error(`Not a public demo dependency: ${relative}`);
    const id=modules.length;ids.set(filename,id);modules.push('');
    const source=fs.readFileSync(filename,'utf8').replace(/require\(['"]([^'"]+)['"]\)/g,(_,specifier)=>{
      if(specifier==='@xmldom/xmldom')return 'browserXml';
      const next=specifier==='fflate'?path.join(ROOT,'node_modules/fflate/lib/browser.cjs'):
        specifier==='diff'?path.join(ROOT,'node_modules/diff/libcjs/diff/word.js'):
        specifier.startsWith('.')?require.resolve(path.resolve(path.dirname(filename),specifier)):null;
      if(!next)throw new Error(`Unsupported browser dependency: ${specifier}`);
      return `load(${add(next)})`;
    });
    modules[id]=`function(module,exports){\n${source}\n}`;return id;
  }
  const entry=add(path.join(ROOT,'assets/static-demo-entry.cjs'));
  return `/* Generated by scripts/build-static.cjs. Dependency licenses: THIRD-PARTY-LICENSES.txt */
(()=>{'use strict';
const Buffer={from:value=>new Uint8Array(value)};
const browserXml={XMLSerializer:window.XMLSerializer,DOMParser:class{
  parseFromString(source,type){const parsed=new window.DOMParser().parseFromString(source,type);if(parsed.getElementsByTagName('parsererror').length)throw new Error('문서 XML을 읽을 수 없습니다. 손상되지 않은 체험용 DOCX를 사용해 주세요.');return parsed;}
}};
const modules=[${modules.join(',\n')}],cache={};
function load(id){if(cache[id])return cache[id].exports;const module={exports:{}};cache[id]=module;modules[id](module,module.exports);return module.exports;}
load(${entry});
})();\n`;
}
function html(){
  const dom=new JSDOM(fs.readFileSync(path.join(ROOT,'index.html'),'utf8'));
  const d=dom.window.document,$=selector=>{const e=d.querySelector(selector);if(!e)throw new Error(`Missing demo element: ${selector}`);return e;};
  const text=(s,v)=>$(s).textContent=v;
  d.documentElement.dataset.runtime='static-demo';
  text('title','NDA Studio — 인터랙티브 데모');
  $('meta[name=description]').content='가상의 NDA로 조건 설정, 17개 검토 항목, 권고 채택과 Word 변경내용 추적을 체험하세요. 모든 처리는 브라우저 안에서 이루어집니다.';
  const script=d.createElement('script');script.defer=true;script.src='assets/static-demo.js';$('script').before(script);
  text('#connection-status','브라우저 데모');text('#setup-button','데모 안내 ↗');text('#setup-inline','데모 안내 →');
  text('.workspace-edition','INTERACTIVE DEMO');
  text('.hero-subtitle','비밀유지계약(NDA) 검토 · 인터랙티브 데모');
  $('.hero-description').innerHTML='가상의 NDA로 검토 흐름을 체험하세요.<br>우리 회사와 원하는 조건을 선택하고,<br>변경 이력이 담긴 Word 수정본을 받아보세요.';
  text('.hero-tags span:nth-child(2)','한글 · 영문 입력');
  text('.upload-card-badge','체험용 계약');text('.upload-card h2','예시 NDA로 시작해 보세요.');
  text('.upload-card > p.muted','Lumen · Northstar의 가상 계약입니다. 실제 AI 검토는 제공하지 않습니다.');
  text('#drop-zone strong','체험용 NDA 파일을 놓아주세요');text('.upload-types','예시 DOCX 전용 · 최대 10MB');
  $('#file-input').accept='.docx,application/vnd.openxmlformats-officedocument.wordprocessingml.document';
  text('#upload-button','예시 문서 확인 →');
  text('.privacy-copy','문서와 입력은 이 브라우저 안에서만 처리합니다.\n새로고침하거나 체험을 초기화하면 자료가 사라집니다.');
  const sample=d.createElement('button');sample.id='sample-download';sample.type='button';sample.className='text-button';sample.textContent='체험용 NDA 받기 ↓';$('#drop-zone').before(sample);
  text('.demo-entry > span','파일 없이 바로 시작하려면');$('#demo-button').className='button primary';
  text('.language-hint','한글·영문 입력을 그대로 삽입합니다. AI 의미 해석이나 번역은 수행하지 않습니다.');
  text('#delete-case','브라우저 자료 지우기');
  text('.final-note','체험용 가상 계약의 수정본입니다. 실제 법률검토 결과나 체결용 계약서가 아닙니다.');
  text('#busy-overlay .micro','체험용 문서와 수정본을 브라우저에서 처리합니다.');
  text('#guide-dialog .guide-steps li:first-child p','「예시로 체험하기」로 시작하거나 제공된 체험용 DOCX를 내려받아 업로드하세요.');
  text('#guide-dialog .guide-bottom .pill:first-child','체험용 DOCX');
  $('#setup-dialog').innerHTML='<div class="dialog-heading"><h2>브라우저에서 완성하는 데모</h2><button id="close-setup" type="button" class="icon-button" aria-label="데모 안내 닫기">×</button></div><p>가상의 회사와 NDA로 제품의 네 단계를 체험합니다. 서버 연결이나 API 키 설정 없이 사용할 수 있습니다.</p><ol class="setup-steps"><li>예시로 시작하거나 체험용 DOCX를 내려받아 다시 업로드합니다.</li><li>대리 회사와 원하는 조건을 선택합니다. 한글·영문 입력은 번역 없이 그대로 반영됩니다.</li><li>준비된 17개 검토 항목과 수정 내역을 확인하고 추가 권고를 채택합니다.</li><li>실제 Word 변경내용 추적이 담긴 V1·V2를 다운로드합니다.</li></ol><p class="notice">일반 NDA의 AI 분석·법률 판단·DOC 변환은 제공하지 않습니다. 다른 계약을 올려도 예시 결과로 대체하지 않습니다.</p><p class="muted">자료는 현재 탭의 메모리에만 있습니다. 새로고침 또는 초기화 시 지워지며, 다운로드한 파일은 컴퓨터에 남습니다.</p>';
  const result=dom.serialize();dom.window.close();return result;
}
function build(){
  if(path.dirname(OUTPUT)!==ROOT||path.basename(OUTPUT)!=='dist')throw new Error('Unexpected build path');
  if(fs.existsSync(OUTPUT)){
    if(fs.lstatSync(OUTPUT).isSymbolicLink()||!fs.existsSync(path.join(OUTPUT,'.nda-static-build')))throw new Error('dist exists and was not created by this build. Move it before building.');
    fs.rmSync(OUTPUT,{recursive:true,force:true});
  }
  fs.mkdirSync(path.join(OUTPUT,'assets'),{recursive:true});
  fs.writeFileSync(path.join(OUTPUT,'.nda-static-build'),'Generated static demo only.\n');
  fs.writeFileSync(path.join(OUTPUT,'index.html'),html());
  fs.writeFileSync(path.join(OUTPUT,'assets/static-demo.js'),bundle());
  for(const name of ['studio.js','studio.css'])fs.copyFileSync(path.join(ROOT,'assets',name),path.join(OUTPUT,'assets',name));
  const licenses=['diff','fflate'].map(name=>`${name}\n${fs.readFileSync(path.join(ROOT,'node_modules',name,'LICENSE'),'utf8')}`).join('\n\n');
  fs.writeFileSync(path.join(OUTPUT,'THIRD-PARTY-LICENSES.txt'),licenses);
  console.log('Static demo built: dist/index.html (no API, no credentials, no runtime server)');
  return OUTPUT;
}
if(require.main===module)build();
module.exports={build};
